#
# Drupal Console tooling.
#
drupal-console:
  image: bmcclure/drupalconsole:1.0
  command: 'true'
  volumes:
    - $KALABOX_APP_ROOT/code:/app
    - $KALABOX_APP_ROOT/config/drupal-console:/root
  working_dir: /app
  stdin_open: true
  tty: true
