#
# Drupal Console tooling.
#
drupal-console:
  image: bmcclure/drupalconsole:latest
  command: 'true'
  volumes:
    - $KALABOX_APP_ROOT_BIND:/src
    - $KALABOX_APP_ROOT/config/drupal-console:/root
  volumes_from:
    - data
  environment:
    HOSTNAME: $KALABOX_APP_HOSTNAME
  working_dir: /src/code
  stdin_open: true
  tty: true
