#
# Drupal Console tooling.
#
drupal-console:
  image: drupalconsole/console:master
  command: 'true'
  volumes:
    - $KALABOX_APP_ROOT:/app
    - $KALABOX_APP_ROOT/config/drupal-console:/root
  working_dir: /app
  stdin_open: true
  tty: true
